using System;

namespace Cave.CodeGen;

/// <summary>
/// Marks a structure or class for autogenerated overrides of GetHashCode, Equals and implementation of IEquatable&lt;&gt;.
/// </summary>
[AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct)]
public class GenerateDefaultFunctionsAttribute : Attribute
{
}
